### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by daktak** [theguardian/KodiDB#2]
Traceback (most recent call last):
  File "/home/daktak/KodiDB/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/daktak/KodiDB/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/home/daktak/KodiDB/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/daktak/KodiDB/cherrystrap/webServe.py", line 499, in tvshows
    if int(episode['c05'].replace('-','')) >= ref_date:
AttributeError: 'NoneType' object has no attribute 'replace'

I had to edit dbMap as my databases are MyMusic48 and MyVideos90 not xbmc_

**Comment by daktak** [comment]
Traceback (most recent call last):
  File "/home/daktak/KodiDB/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/daktak/KodiDB/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/home/daktak/KodiDB/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/daktak/KodiDB/cherrystrap/webServe.py", line 444, in movies
    movieRateArr = movie['c12'].replace('Rated ','').split(' for ')
AttributeError: 'NoneType' object has no attribute 'replace'
